- "torch"
- "torchvision"
- "opencv-python==4.12.0.88"
- "pillow==12.0.0"
- "matplotlib==3.10.7"
- "scikit-learn==1.7.2"
- "albumentations==2.0.8"
- "tqdm==4.67.1"
- "onnx==1.19.1"
- "tensorflow==2.20.0"
- "psutil==7.1.3"
- "sympy==1.14.0"
- "six==1.17.0"
- "sng4onnx==1.0.4"