- "torch"
- "torchvision"
- "opencv-python"
- "pillow"
- "Matplotlib"
- "scikit-learn"
- "albumentations"
- "tqdm"
- "onnx"
- "tensorflow"
- "tf_keras"
- "psutil"
- "sympy"
- "six"
- "onnx-graphsurgeon"
- "sng4onnx"